### ISSUE TITLE
Incompatibility with the Python version in handling underscores

### ISSUE THREAD

**Issue by DoronRippel** [xdrop/fuzzywuzzy#97]
The FuzzySearch.tokenSetPartialRatio() method returns different results than the Python version for strings that contain **underscore**.

Examples:

- FuzzySearch.tokenSetPartialRatio("worm_mikeala", "mikeala rath") returns 74 while the Python version returns 58
- FuzzySearch.tokenSetPartialRatio("c_wasyluka", "crystal wasyluka") returns 100 while the Python version returns 80

**Comment by xdrop** [comment]
Thanks, I have pushed a commit to fix this. I'll release this in a new version.

**Comment by DoronRippel** [comment]
Hi Panayiotis,

I saw that there was a new version 1.3.4, so I assumed that this is where
you fixed the issue and I used it, but the issue is not only not fixed -
all the examples now return 100...

Here is how I run them in Java:
System.out.println("expected 58 -> got " +
FuzzySearch.tokenSetPartialRatio("worm_mikeala", "mikeala rath"));
System.out.println("expected 80 -> got " +
FuzzySearch.tokenSetPartialRatio("c_wasyluka", "crystal wasyluka"));
System.out.println( "expected 78 -> got " +
FuzzySearch.tokenSetPartialRatio("a_bacdefg", "crystal bacdefg"));
I get:
expected 58 -> got 100
expected 80 -> got 100
expected 78 -> got 100

and here is how I run them in Python:

from fuzzywuzzy import fuzz

if __name__ == '__main__':

    print(fuzz.partial_token_set_ratio("worm_mikeala", "mikeala rath"))
    print(fuzz.partial_token_set_ratio("c_wasyluka", "crystal wasyluka"))
    print(fuzz.partial_token_set_ratio("x_bacdefg", "crystal bacdefg"))
I get:
58
80
78


Thank you,

Doron
